var window = {};
eval(require('fs').readFileSync('site/data/portal_data.js','utf8'));
var txt = require('fs').readFileSync('site/portal_app.js','utf8');
var s = txt.indexOf('/* ===== TIMELINE:'), e = txt.indexOf('/* ===== END TIMELINE =====');
eval(txt.substring(s, e));
var data = buildTimelineData(window.PORTAL_DATA.unis);
console.log('Summer bars:', data.summer.length, '| Vague:', data.vagueSum.length);
console.log('Winter bars:', data.winter.length, '| Vague:', data.vagueWin.length);
console.log('\n=== SUMMER ===');
data.summer.forEach(function(e) { console.log('  ' + e.uni.abbr.padEnd(26) + ' M' + e.parsed.startMonth + '/' + (e.parsed.startDay||'?') + ' - M' + e.parsed.endMonth + '/' + (e.parsed.endDay||'?') + (e.parsed.approx ? ' ~' : '')); });
console.log('\n=== VAGUE SUMMER (' + data.vagueSum.length + ') ===');
data.vagueSum.forEach(function(u) { console.log('  ' + u.abbr.padEnd(26) + (u.summer||'').substring(0,55)); });
console.log('\n=== WINTER ===');
data.winter.forEach(function(e) { console.log('  ' + e.uni.abbr.padEnd(26) + ' M' + e.parsed.startMonth + '/' + (e.parsed.startDay||'?') + ' - M' + e.parsed.endMonth + '/' + (e.parsed.endDay||'?') + (e.parsed.approx ? ' ~' : '')); });
console.log('\n=== VAGUE WINTER (' + data.vagueWin.length + ') ===');
data.vagueWin.forEach(function(u) { console.log('  ' + u.abbr.padEnd(26) + (u.winter||'').substring(0,55)); });
